name: EmeraldArmorPlugin
version: '1.1'
main: net.godlycow.org.emeraldarmorplugin.EmeraldArmorPlugin
api-version: 1.20
author: _GodlyCow
website: https://net.godlycow.org/emerald%E2%80%91armor%E2%80%91plugin.html
